### ISSUE TITLE
Ignored & inactive / unchanged files not distinguishable

### ISSUE THREAD

**Issue by CHE1RON** [mikasius/zed-nord-theme#10]
Hey there,

first of all, I loaded this from the Zed extensions and love it - one thing I noticed though, as the title already gives away: (git)ignored files look just the same as inactive/unchanged files.

Other extensions/themes differentiate between those two, eg 

"One Dark" 
<img width="260" alt="Screenshot 2024-08-22 at 18 23 23" src="https://github.com/user-attachments/assets/6b239114-a299-44e9-9c67-1bd8927edc81">

"Solarized Dark"
<img width="226" alt="Screenshot 2024-08-22 at 18 24 01" src="https://github.com/user-attachments/assets/8a4bb871-9435-4037-b0af-2c5116b05b26">

For comparison: "Nord" on VSCode:
<img width="273" alt="Screenshot 2024-08-22 at 18 25 19" src="https://github.com/user-attachments/assets/a2b8529b-67dd-420b-ac2e-b016d07d4d3e">

Maybe changing that is something to consider? 😊 🙏

**Comment by hedgieinsocks** [comment]
I have managed to tackle this via the following override:

```json
"experimental.theme_overrides": {
    "ignored": "#4c566a",
  },
```

But this might feel 'too hidden', so you can experiment with other colors.

**Comment by CHE1RON** [comment]
I'll play around with it, thanks! Although I get the feeling that ignored files should be distinguishable by default 🤔

**Comment by mikasius** [comment]
@CHE1RON 
I plan to integrate this changes soon. :) 
Right now rather busy. :)

Thank you for your suggestion and help.

**Comment by CHE1RON** [comment]
Much appreciated!

**Comment by mikasius** [comment]
Already in PR https://github.com/zed-industries/extensions/pull/1429

**Comment by mikasius** [comment]
Should be already in new theme version. :) Thank you guys!
