### ISSUE TITLE
Coloring of github copilot when using the suggestion function.

### ISSUE THREAD

**Issue by yasainet** [mikasius/zed-nord-theme#12]
Nice to meet you!
As the title says, I would like to set up the coloring of the suggestion display of github copilot.

As the screenshot shows an example, I would like to change the coloring of the suggestions displayed.

![image](https://github.com/user-attachments/assets/e4db8896-684f-4b9a-aeec-dd9de3484a3b)

Is it easier to use if the coloring is aligned with the coloring used in the comment out?

I would like to know how to set this up or if there are plans to update this in the future.

**Comment by cloud303-cholden** [comment]
It looks there are theme settings for this. See https://github.com/zed-industries/zed/issues/17915#issuecomment-2368973212. I wasn't able to get `experimental.theme_overrides` to work, so it might be necessary to add the following to the theme: `"predictive": "#616E88"`.

**Comment by yasainet** [comment]
thank you!!
