### ISSUE TITLE
On current zed version (0.154.2), dark theme cursor is nearly invisible

### ISSUE THREAD

**Issue by jonathanjsimon** [mikasius/zed-nord-theme#14]
The slightly lighter gray bar after the semicolon in this shot is the cursor. Other dark themes have a white cursor and this theme used to show a white cursor as well.

![Screenshot_20240926_204941](https://github.com/user-attachments/assets/5e0faad3-d509-43c4-a493-162920c6a582)

**Comment by yasainet** [comment]
I responded by adding the following settings
I hope this will be helpful.

`~/.config/zed/settings.json`

```json
"experimental.theme_overrides": {
    "players": [
      {
        "cursor": "#eceff4"
      }
    ]
  }
```

**Comment by apognu** [comment]
Workaround works, thanks, that is a lifesaver until the theme is fixed. 🙏
