### ISSUE TITLE
Search Highlight Contrast & Other General Highlighting

### ISSUE THREAD

**Issue by Taklop** [mikasius/zed-nord-theme#4]
Thanks so much for creating this, Nord is one of my fave themes!

I just had a little feedback for a couple of things I noticed:
 ## Search
When searching in a file, the highlighted matches are very hard to spot currently. The "currently" highlighted match is okay-enough, but the other matches could maybe be more contrasty.

Below is a comparison of Nord in Zed vs Nord in vscode:
### Zed Nord
![CleanShot 2024-04-15 at 12 19 37](https://github.com/mikasius/zed-nord-theme/assets/10657260/1253a99a-d1ed-4c68-91bb-c54166f3e98b)

### VSCode Nord
![CleanShot 2024-04-15 at 12 17 48](https://github.com/mikasius/zed-nord-theme/assets/10657260/053e094b-d016-474b-8564-4129593f1044)

## General Highlighting
It seems that the zed implementation of Nord doesn't use as much of the palette as it could to help differentiate items & add contrast. (Some areas it is *better* than the VSCode version though!

I'm unsure if this is a limitation in Zed, the langserver / svelte plugin though, but thought I'd mention. Here are some examples

### Zed Vs VSCode Nord
![CleanShot 2024-04-15 at 12 27 07](https://github.com/mikasius/zed-nord-theme/assets/10657260/fda7ab63-6865-40cf-8009-5a1ec3cca43a)

**Comment by mikasius** [comment]
@Taklop 
Thank you for this detailed overview!
Right now a have not much time to develop this. I'll returned to this later. 
If you have a time, you could create a PR for this changes and I will merge it. :)

**Comment by mikasius** [comment]
I've checked this out and as I can see is everything is ok in current version (Zed 0.144.4) of Zed.
I'll plan to update dark variant of theme soon. Just minor improvements. 
![image](https://github.com/user-attachments/assets/03079a88-1041-455e-9b20-2fa2f3a07ab7)
