### ISSUE TITLE
Compiler warning hovercard is unreadable due to card background

### ISSUE THREAD

**Issue by jonathanjsimon** [mikasius/zed-nord-theme#6]
It appears to be a theme issue because other themes don't have this issue. Thanks!

![Screenshot_20240802_134901](https://github.com/user-attachments/assets/78d62b5e-2802-4c55-ba2b-461aaef105db)

**Comment by mikasius** [comment]
As I can see, it was fixed in latest version 0.0.7
Please, try to update.
