### ISSUE TITLE
Transparent titlebar when losing focus on Gnome Wayland

### ISSUE THREAD

**Issue by hedgieinsocks** [mikasius/zed-nord-theme#7]
Hi, could you please help me pinpoint the variable to tweak the color of the inactive titlebar? 
The issue is that currently it seems to become transparent when losing focus.
Here you can see that once I opened Eyedropper app, zed titlebar became transparent, showing the underlying firefox window.
![glitch](https://github.com/user-attachments/assets/1d635603-9a6b-4a44-8c2d-503a117e1284)

**Comment by hedgieinsocks** [comment]
UPD: I've solved my issue by adding `"title_bar.inactive_background": "#2e3440"`

**Comment by hedgieinsocks** [comment]
Just noticed `Linux: Changed the fallback color of title_bar.inactive_background to a non-transparent value.` in https://github.com/zed-industries/zed/releases/tag/v0.148.0-pre

**Comment by mikasius** [comment]
Ok, I'm glad that you solved the issue.

**Comment by mikasius** [comment]
@hedgieinsocks solved it via `"title_bar.inactive_background": "#2e3440"`
